export const products = [
  {
    id: "p1",
    name: "Apple",
    price: 99,
    emoji: "🍎",
    description: "Fresh and sweet apples, perfect for snacks and desserts.",
  },
  {
    id: "p2",
    name: "Banana",
    price: 109,
    emoji: "🍌",
    description: "Soft bananas with natural sweetness and rich energy.",
  },
  {
    id: "p3",
    name: "Orange",
    price: 149,
    emoji: "🍊",
    description: "Juicy oranges full of fresh citrus flavour.",
  },
  {
    id: "p4",
    name: "Grape",
    price: 49,
    emoji: "🍇",
    description: "Small and refreshing grapes for everyday eating.",
  },
  {
    id: "p5",
    name: "Strawberry",
    price: 129,
    emoji: "🍓",
    description: "Bright red strawberries with a sweet and fresh taste.",
  },
  {
    id: "p6",
    name: "Blueberry",
    price: 79,
    emoji: "🫐",
    description: "Fresh blueberries, ideal for breakfast or smoothies.",
  },
  {
    id: "p7",
    name: "Kiwi",
    price: 159,
    emoji: "🥝",
    description: "Green kiwi fruit with a fresh sweet and sour flavour.",
  },
  {
    id: "p8",
    name: "Pineapple",
    price: 299,
    emoji: "🍍",
    description: "Tropical pineapple with a strong sweet flavour.",
  },
];